-- Run this once in Supabase SQL Editor
create table if not exists public.routine_dashboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(user_id)
);

alter table public.routine_dashboard enable row level security;

drop policy if exists "Users can read own routine" on public.routine_dashboard;
create policy "Users can read own routine" on public.routine_dashboard
for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own routine" on public.routine_dashboard;
create policy "Users can insert own routine" on public.routine_dashboard
for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own routine" on public.routine_dashboard;
create policy "Users can update own routine" on public.routine_dashboard
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
